name: "Fix yaml in another repository"
author: JunHCha <quffl9612@alphaprime.co.kr>
description: "Fix yaml file in another repository with the given key and value."
inputs:
  token:
    description: The Github access token.
    required: true
  target_repository:
    description: The Git repository which has target yaml file.
    required: true
  file_path:
    description: The path for the target values file to be modified.
    required: true
  target_branch:
    description: The target branch of the git repository to modify.
    required: true
  commit_message:
    description: Commit message.
    default: Update yaml file
    required: false
  key_val_pairs:
    description: key-value pairs to update.
    required: true

runs:
  using: "docker"
  image: Dockerfile
